# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp-Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeatherApp-Test
	pod 'AFNetworking', '~> 3.0'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
    pod 'SDWebImage', '~> 4.0'
end
